services:
  - type: web
    name: project-oracle
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: ORACLE_HOST_CODE
        value: ORACLE-GM-1
